version: "3.8"

services:
  django:
    container_name: django
    build:
      context: ./
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8020 --workers 4 --log-level debug --reload
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8020:8020
    env_file:
      - ./docker.env

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379" # Expose Redis port to the host machine

  flower:
    image: mher/flower
    restart: always
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  celery:
    container_name: celery
    restart: always
    build:
      context: ./
    #    command: celery --app=core worker -l INFO -B
    command: celery --app=core worker -l INFO -B
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./docker.env
